pit.loadlib("libi2c")
lcd = pit.loadlib("liblcd")
display = pit.loadlib("libdisplay")
lcd_handle = lcd.create(1, 0x27, 16, 2)
display.cls(lcd_handle)
display.print(lcd_handle, 0, 0, "TEST")
pit.finish(0)
