pit.loadlib("libi2c")
oled = pit.loadlib("libsd1306")
display = pit.loadlib("libdisplay")
handle = oled.create(1, 0x3C)
display.enable(handle, true)
display.font(handle, 4)
display.cls(handle)
display.print(handle, 0, 0, "Test")
pit.finish(0)
